#pragma once
#include <stdint.h>
#ifndef GLASSES_CONFIDENCE_RULE_TYPE_DEFINED
#define GLASSES_CONFIDENCE_RULE_TYPE_DEFINED
struct GlassesConfidenceRule {
    const char* company; const char* product; uint8_t confidence; int32_t companyId;
    const char* macExact; const char* manufacturerHex; uint16_t serviceUuid16;
    const char* namePattern; bool exactName; uint32_t oui24; bool hasCamera;
    bool cameraKnown; const char* reason;
};
#endif
static const GlassesConfidenceRule MEDIUM_CONFIDENCE_RULES[] = {
    { "Meta Platforms", "Meta smart-glasses candidate", 75, -1, nullptr, nullptr, 0xFD5F, nullptr, false, 0, true, false, "Meta-assigned service UUID" },
    { "Meta Platforms Technologies", "Meta smart-glasses candidate", 70, -1, nullptr, nullptr, 0, nullptr, false, 0x7C2A9E, true, false, "Meta OUI prefix" },
    { "Meta Platforms Technologies", "Meta smart-glasses candidate", 70, -1, nullptr, nullptr, 0, nullptr, false, 0xCC660A, true, false, "Meta OUI prefix" },
    { "Meta Platforms Technologies", "Meta smart-glasses candidate", 70, -1, nullptr, nullptr, 0, nullptr, false, 0xF40343, true, false, "Meta OUI prefix" },
    { "Meta Platforms Technologies", "Meta smart-glasses candidate", 70, -1, nullptr, nullptr, 0, nullptr, false, 0x5CE91E, true, false, "Meta OUI prefix" },
    { "Luxottica Group", "Luxottica smart-glasses candidate", 72, -1, nullptr, nullptr, 0, nullptr, false, 0x985949, true, false, "Luxottica OUI prefix" },
    { "Meta", "Meta Ray-Ban", 85, -1, nullptr, nullptr, 0, "rayban", false, 0, true, true, "Ray-Ban advertised-name match" },
    { "Meta", "Meta Ray-Ban", 85, -1, nullptr, nullptr, 0, "ray-ban", false, 0, true, true, "Ray-Ban advertised-name match" },
    { "Meta", "Meta Ray-Ban", 85, -1, nullptr, nullptr, 0, "ray ban", false, 0, true, true, "Ray-Ban advertised-name match" },
    { "Meta", "Meta Ray-Ban", 85, -1, nullptr, nullptr, 0, "meta_rb", false, 0, true, true, "Meta Ray-Ban advertised-name match" },
    { "Snap", "Snap Spectacles", 85, -1, nullptr, nullptr, 0, "spectacles", false, 0, true, true, "Spectacles advertised-name match" },
    { "Vuzix", "Vuzix Glasses", 85, -1, nullptr, nullptr, 0, "vuzix", false, 0, true, true, "Vuzix advertised-name match" },
    { "Epson", "Epson Moverio", 85, -1, nullptr, nullptr, 0, "moverio", false, 0, true, true, "Moverio advertised-name match" },
    { "North", "North Focals", 82, -1, nullptr, nullptr, 0, "focals", false, 0, false, true, "Focals advertised-name match" },
    { "Amazon", "Amazon Echo Frames", 82, -1, nullptr, nullptr, 0, "echo frames", false, 0, false, true, "Echo Frames advertised-name match" },
    { "TCL", "TCL RayNeo", 85, -1, nullptr, nullptr, 0, "rayneo", false, 0, true, true, "RayNeo advertised-name match" },
    { "Solos", "Solos AirGo", 82, -1, nullptr, nullptr, 0, "solos", false, 0, false, true, "Solos advertised-name match" },
    { "Even Realities", "Even Realities", 80, -1, nullptr, nullptr, 0, "even g", false, 0, false, true, "Even Realities advertised-name match" },
    { "INMO", "INMO Air", 80, -1, nullptr, nullptr, 0, "inmo", false, 0, false, true, "INMO advertised-name match" },
    { "Rokid", "Rokid Glasses", 80, -1, nullptr, nullptr, 0, "rokid", false, 0, false, true, "Rokid advertised-name match" },
    { "XREAL", "Xreal Air", 80, -1, nullptr, nullptr, 0, "xreal", false, 0, false, true, "XREAL advertised-name match" },
    { "XREAL", "Xreal (Nreal)", 80, -1, nullptr, nullptr, 0, "nreal", false, 0, false, true, "Nreal advertised-name match" },
    { "HeyCyan", "HeyCyan", 85, -1, nullptr, nullptr, 0, "HeyCyan", false, 0, true, true, "HeyCyan advertised-name match" },
    { "Google", "Google Glass", 85, -1, nullptr, nullptr, 0, "Google Glass", false, 0, true, true, "Google Glass advertised-name match" },
    { "Luxottica", "Possible Luxottica Smart Glasses", 72, -1, nullptr, nullptr, 0, "Luxottica", false, 0, true, false, "Luxottica advertised-name clue" },
    { "Kmart Australia Limited / Anko", "Anko Camera Glasses 43700141 (JLR-82067)", 89, -1, nullptr, nullptr, 0, "Anko43700141", true, 0, true, true, "Official Kmart Camera Glasses Bluetooth name (item 43700141)" },
    { "Kmart / Anko", "Kmart / Anko Glasses", 75, -1, nullptr, nullptr, 0, "Kmart Glasses", false, 0, true, false, "Kmart Glasses name" },
    { "Anko", "Anko Camera Glasses", 75, -1, nullptr, nullptr, 0, "Anko Glasses", false, 0, true, false, "Anko Glasses name" },
    { "Unknown", "AI Glasses", 68, -1, nullptr, nullptr, 0, "AI Glasses", false, 0, true, false, "Generic AI Glasses name" },
    { "Kmart", "Possible Kmart Glasses", 65, -1, nullptr, nullptr, 0, "Kmart", false, 0, true, false, "Broad Kmart name clue" },
    { "Anko", "Possible Anko Glasses", 65, -1, nullptr, nullptr, 0, "Anko", false, 0, true, false, "Broad Anko name clue" },
    { "Unknown", "Possible Glasses", 65, -1, nullptr, nullptr, 0, "Glasses", false, 0, true, false, "Generic Glasses keyword" },
    { "Unknown", "AI device / possible glasses", 60, -1, nullptr, nullptr, 0, "AI", true, 0, true, false, "Exact AI advertised name" },
    { "Meta / Ray-Ban", "Ray-Ban Smart Glasses", 85, -1, nullptr, nullptr, 0, "Ray-Ban Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Meta / Ray-Ban", "Ray-Ban Smart Glasses", 85, -1, nullptr, nullptr, 0, "Ray Ban Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Meta Platforms", "Meta Smart Glasses", 85, -1, nullptr, nullptr, 0, "Meta Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Luxottica Group", "Luxottica Smart Glasses", 82, -1, nullptr, nullptr, 0, "Luxottica Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Oakley / Luxottica", "Oakley Smart Glasses", 85, -1, nullptr, nullptr, 0, "Oakley Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Snap", "Snap Smart Glasses", 85, -1, nullptr, nullptr, 0, "Snap Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Snapchat", "Snap Spectacles", 85, -1, nullptr, nullptr, 0, "Snapchat Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Snap", "Snap Spectacles", 85, -1, nullptr, nullptr, 0, "Spectacles Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Vuzix", "Vuzix Smart Glasses", 85, -1, nullptr, nullptr, 0, "Vuzix Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "HeyCyan", "HeyCyan Smart Glasses", 85, -1, nullptr, nullptr, 0, "HeyCyan Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Google", "Google Glass", 82, -1, nullptr, nullptr, 0, "Google Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "TCL", "TCL / RayNeo Smart Glasses", 82, -1, nullptr, nullptr, 0, "TCL Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "TCL / RayNeo", "RayNeo Smart Glasses", 85, -1, nullptr, nullptr, 0, "RayNeo Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Meizu", "Meizu / MYVU Smart Glasses", 82, -1, nullptr, nullptr, 0, "Meizu Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Meizu / MYVU", "MYVU AR Glasses", 82, -1, nullptr, nullptr, 0, "MYVU Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "North", "North Smart Glasses", 80, -1, nullptr, nullptr, 0, "North Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { "North", "North Focals", 82, -1, nullptr, nullptr, 0, "Focals Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { "Kopin", "Kopin Smart Glasses", 80, -1, nullptr, nullptr, 0, "Kopin Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { "Solos / Kopin", "Solos AirGo", 82, -1, nullptr, nullptr, 0, "Solos Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { "Sony", "Sony SmartEyeglass", 82, -1, nullptr, nullptr, 0, "Sony Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Epson", "Epson Moverio Smart Glasses", 82, -1, nullptr, nullptr, 0, "Epson Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Epson", "Epson Moverio Smart Glasses", 85, -1, nullptr, nullptr, 0, "Moverio Glasses", false, 0, true, true, "Brand + Glasses fallback" },
    { "Apple", "Possible Apple Smart Glasses", 65, -1, nullptr, nullptr, 0, "Apple Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Xiaomi", "Possible Xiaomi Smart Glasses", 65, -1, nullptr, nullptr, 0, "Xiaomi Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Oppo", "Possible Oppo Smart Glasses", 65, -1, nullptr, nullptr, 0, "Oppo Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Huawei", "Possible Huawei Smart Glasses", 65, -1, nullptr, nullptr, 0, "Huawei Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Samsung", "Possible Samsung Smart Glasses", 65, -1, nullptr, nullptr, 0, "Samsung Glasses", false, 0, false, false, "Brand + Glasses fallback" },
    { "Amazon", "Possible Amazon Smart Glasses", 65, -1, nullptr, nullptr, 0, "Amazon Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Bose", "Possible Bose Frames", 70, -1, nullptr, nullptr, 0, "Bose Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { "Lenovo", "Possible Lenovo Smart Glasses", 65, -1, nullptr, nullptr, 0, "Lenovo Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "HTC", "Possible HTC Smart Glasses", 65, -1, nullptr, nullptr, 0, "HTC Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "ByteDance", "Possible ByteDance Smart Glasses", 65, -1, nullptr, nullptr, 0, "ByteDance Glasses", false, 0, true, false, "Brand + Glasses fallback" },
    { "Razer", "Possible Razer Smart Glasses", 70, -1, nullptr, nullptr, 0, "Razer Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { "Fauna Audio", "Fauna Glasses", 70, -1, nullptr, nullptr, 0, "Fauna Glasses", false, 0, false, true, "Brand + Glasses fallback" },
    { nullptr, nullptr, 0, -1, nullptr, nullptr, 0, nullptr, false, 0, false, false, nullptr }
};
